name: MX
version: '4.3 (Mintia)'
api-version: '1.13'
author: pawsashatoy
description: "Complex combat analysis anti-cheat"
main: kireiko.dev.anticheat.MX
depend: [ ProtocolLib ]
commands:
  mx:
    description: "Main command"
    usage: "/mx"
    permission: "mx.admin"
    aliases: [ mx ]
